#!/usr/bin/env bash
export GOPATH="$HOME/work"
export PATH="$GOPATH/bin:$PATH"

export GOENV_ROOT="${GOENV_ROOT:=${HOME}/.goenv}"
if ! type goenv > /dev/null  2>&1 && [ -f "${GOENV_ROOT}/bin/goenv" ]; then
    export PATH="${GOENV_ROOT}/bin:${PATH}"
fi

if type -t goenv &> /dev/null; then
    GOENV_SHIMS="${GOENV_ROOT:-${HOME}/.goenv}/shims"
    export PATH="${GOENV_SHIMS}:${PATH}"
    source $(dirname $(greadlink -f $(which goenv)))/../completions/goenv.bash
    function goenv() {
        unset -f goenv > /dev/null 2>&1
        eval "$(command goenv init -)"
        goenv "$@"
    }
fi
