#!/usr/bin/env bash
_lazynvm() {
    unset -f nvm node npm npx
    . "/usr/local/opt/nvm/nvm.sh"
}

nvm() {
    _lazynvm
    nvm "$@"
}

node() {
    _lazynvm
    node "$@"
}

npm() {
    _lazynvm
    npm "$@"
}

npx() {
    _lazynvm
    npx "$@"
}

if [ -e  "/usr/local/opt/nvm/nvm.sh" ] ; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"
    [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"
else
    unset -f nvm node npm npx _lazynvm
fi
