#!/usr/bin/env bash
export PYENV_ROOT="${PYENV_ROOT:=${HOME}/.pyenv}"
if ! type pyenv > /dev/null && [ -f "${PYENV_ROOT}/bin/pyenv" ]; then
    export PATH="${PYENV_ROOT}/bin:${PATH}"
fi

# Lazy load pyenv
if type pyenv > /dev/null; then
    export PATH="${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${PATH}"
    source $(dirname $(greadlink -f $(which pyenv)))/../completions/pyenv.bash
    function pyenv() {
        unset -f pyenv
        eval "$(command pyenv init -)"
        pyenv "$@"
    }
fi

if type pyenv-virtualenv &> /dev/null; then
  function pyenv-virtualenv() {
    unset -f pyenv-virtualenv > /dev/null 2>&1
    eval "$(command pyenv virtualenv-init -)"
    pyenv-virtualenv "$@"
  }
fi
