#!/usr/bin/env bash
export PHPENV_ROOT="${PHPENV_ROOT:=${HOME}/.phpenv}"
if ! type phpenv > /dev/null  2>&1 && [ -f "${PHPENV_ROOT}/bin/phpenv" ]; then
    export PATH="${PHPENV_ROOT}/bin:${PATH}"
fi

if type phpenv &> /dev/null; then
    PHPENV_SHIMS="${PHPENV_ROOT:-${HOME}/.phpenv}/shims"
    export PATH="${PHPENV_SHIMS}:${PATH}"
    source $(dirname $(greadlink -f $(which phpenv)))/../completions/phpenv.bash
    function phpenv() {
        unset -f phpenv > /dev/null 2>&1
        eval "$(command phpenv init -)"
        phpenv "$@"
    }
fi
