#!/bin/bash
case "$TERM" in
    xterm*|rxvt*)
        TITLEBAR="\[\e]0;λ \w\$git_prompt\a\]"
        ;;
    *)
        TITLEBAR=""
        ;;
esac

GIT_PROMPT_BEFORE=" ("
GIT_PROMPT_AFTER=")"
ENV_PROMPT_BEFORE=":"
ENV_PROMPT_AFTER=""
PROMPT_COMMAND="git_prompt; env_prompt; $PROMPT_COMMAND"
PS1="\\e[0;33mλ\$env_prompt\\e[0m \w\$git_prompt ❯ "
PS1="$TITLEBAR$PS1"

unset TITLEBAR
