#!/bin/bash
case "$TERM" in
    xterm*|rxvt*)
        TITLEBAR="\[\e]0;\w\$git_prompt\a\]"
        ;;
    *)
        TITLEBAR=""
        ;;
esac

PROMPT_COMMAND="find_git_branch; $PROMPT_COMMAND"
PS1="\u@\h:\w\$git_prompt\$ "
PS1="$TITLEBAR$PS1"

unset TITLEBAR
