#!/bin/bash
function arole {
    local name="$1"
    for d in tasks vars defaults handlers files templates meta ; do
        echo mkdir -p "roles/$name/$d"
        mkdir -p "roles/$name/$d"
    done
}

find_git_branch() {
    local dir=.
    local git_branch=''
    until [ "$dir" -ef / ]; do
        if [ -f "$dir/.git/HEAD" ]; then
            head=$(< "$dir/.git/HEAD")
            if [[ $head == ref:\ refs/heads/* ]]; then
                git_branch="${head#*/*/}"
            elif [[ $head != '' ]]; then
                git_branch='detached'
            else
                git_branch='unknown'
            fi
            local git_status=$(git status --porcelain 2> /dev/null)
            if [[ "$git_status" != "" ]]; then
                git_prompt=" ($git_branch*) "
            else
                git_prompt=" ($git_branch) "
            fi
            return
        fi
        dir="../$dir"
    done
    git_prompt=''
}

